media:
- name: images
  label: Images
  input: media/images
  extensions:
  - apng
  - avif
  - gif
  - jpeg
  - jpg
  - png
  - svg
  - webp
content:
- name: guides_categories
  label: Guides - Categories
  type: collection
  path: collections/guides_categories
  fields:
  - name: title
    label: Title
    description: Category name.
    type: text
    required: true
  - name: description
    label: Description
    description: Short category description. USE INLINE STYLES ONLY (LINK, BOLD, ITALIC, STRIKETHROUGH, UNDERLINE)!
    type: rich-text
    options:
      media: false
  - name: identifier
    label: Identifier
    description: Category identifier. DO NOT REGENERATE AFTER CREATION!
    type: uuid
    options:
      editable: false
  filename: "{primary}.yaml"
  view:
    sort:
    - title
    search:
    - title
  format: yaml
  subfolders: false
- name: guides_journeys
  label: Guides - Journeys
  type: collection
  path: collections/guides_journeys
  fields:
  - name: title
    label: Title
    description: Journey name.
    type: text
    required: true
  - name: category
    label: Category
    description: Journey category.
    type: reference
    required: true
    options:
      collection: guides_categories
      search: title
      value: "{identifier}"
      label: "{title}"
  - name: description
    label: Description
    description: Short journey description. USE INLINE STYLES ONLY (LINK, BOLD, ITALIC, STRIKETHROUGH, UNDERLINE)!
    type: rich-text
    options:
      media: false
  - name: steps
    label: Steps
    description: Journey steps.
    type: object
    list:
      collapsible:
        summary: "{index} - {title}"
    required: true
    fields:
    - name: title
      label: Title
      description: Step name.
      type: text
      required: true
    - name: body
      label: Body
      description: Step body. USE H3 HEADING ONLY (DO NOT USE H1 AND H2)!
      type: rich-text
      options:
        media: images
    - name: tasks
      label: Tasks
      description: Step tasks.
      type: object
      list:
        collapsible:
          summary: "{body}"
      fields:
      - name: body
        label: Body
        description: Task body. USE INLINE STYLES ONLY (LINK, BOLD, ITALIC, STRIKETHROUGH, UNDERLINE)!
        type: rich-text
        required: true
        options:
          media: images
      - name: identifier
        label: Identifier
        description: Category identifier. DO NOT REGENERATE AFTER CREATION!
        type: uuid
        options:
          editable: false
    - name: identifier
      label: Identifier
      description: Category identifier. DO NOT REGENERATE AFTER CREATION!
      type: uuid
      options:
        editable: false
  - name: identifier
    label: Identifier
    description: Category identifier. DO NOT REGENERATE AFTER CREATION!
    type: uuid
    options:
      editable: false
  filename: "{primary}.yaml"
  view:
    sort:
    - title
    search:
    - title
  format: yaml
  subfolders: false
settings:
  hide: true
