media:
  categories:
  - image
content:
- name: categories
  label: Categories
  type: collection
  path: collections/guides_categories
  required: true
  list: true
  fields:
  - name: title
    label: Title
    type: rich-text
components:
