media:
  name: images
  label: Images
  input: images
  output: /
  extensions:
  - apng
  - avif
  - gif
  - jpeg
  - jpg
  - png
  - svg
  - webp
content:
- name: guides_categories
  label: Guides - Categories
  type: collection
  path: collections/guides_categories
  fields:
  - name: title
    label: Title
    description: Category name
    required: true
  - name: description
    label: Description
    description: Short category description
    type: rich-text
    options:
      media: false
  filename: {primary}
  view:
    sort:
    - title
    search:
    - title
  format: yaml
  subfolders: false
settings:
  hide: true
